In [53]:
#Description: this program detects if an email is spam (1) or not (0)

In [1]:
#import libraries
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

In [3]:
#Load data
from google.colab import files
uploaded=files.upload()

Saving emails.csv to emails (1).csv


In [4]:
#read the csv file
df=pd.read_csv('emails.csv')
#print the 5 first lignes
df.head(5)

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [7]:
#Print the shape
df.shape

(5728, 2)

In [9]:
df.columns #get columns name

Index(['text', 'spam'], dtype='object')

In [11]:
#check the duplicates and remove them
df.drop_duplicates(inplace=True)

In [12]:
#show the new shape
df.shape

(5695, 2)

In [13]:
#show the number of missing (NAN,na)data for each column
df.isnull().sum()

text    0
spam    0
dtype: int64

In [14]:
#Download the stop package numbers
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [19]:
def process_text(text):
  #remove punctuation
  #remove stopwords
  #return a list of clean text words
  #1
  nopunc=[char for char in text if char not in string.punctuation]
  nopunc=''.join(nopunc)
  #2
  clean_words=[word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
  #3
  return clean_words
 

In [20]:
 #show the tokenization (a list of tokens )
 df['text'].head().apply(process_text)



0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

In [29]:
#Exemple
message1='i m in love with you '
message2='i hate you and love you'
print(message1)
print()
#convert the text to matrix of token counts
from sklearn.feature_extraction.text import CountVectorizer
bow1=CountVectorizer(analyzer=process_text).fit_transform([[message1],[message2]])
print(bow1)
print()
print(bow1.shape)

i m in love with you 

  (0, 1)	1
  (1, 1)	1
  (1, 0)	1

(2, 2)


In [31]:
#convert a collection of text to matrix of tokens 
from sklearn.feature_extraction.text import CountVectorizer
messages_bow=CountVectorizer(analyzer=process_text).fit_transform(df['text'])

In [40]:
#split the data into 80% training and 20% test
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(messages_bow,df['spam'],test_size=0.2,random_state=0) 

In [41]:
#Get the shape messages_bow

messages_bow.shape

(5695, 37229)

In [44]:
#Create and train the Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB 
GN_classifier= MultinomialNB ().fit(X_train, y_train)

In [46]:
#Print the predictions
print(GN_classifier.predict(X_train))
#Print the actual values
print(y_train.values)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [49]:
#Evaluate the model on the training data set
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
pred=GN_classifier.predict(X_train)
print(classification_report(y_train,pred))
print()
print('confusion_matrix: \n',confusion_matrix(y_train,pred))
print()
print('accuracy: \n',accuracy_score(y_train,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3457
           1       0.99      1.00      0.99      1099

    accuracy                           1.00      4556
   macro avg       0.99      1.00      1.00      4556
weighted avg       1.00      1.00      1.00      4556


confusion_matrix: 
 [[3445   12]
 [   1 1098]]

accuracy: 
 0.9971466198419666


In [50]:
#Print the predictions
print(GN_classifier.predict(X_test))
#Print the actual values
print(y_test.values)

[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]


In [52]:
#Evaluate the model on the test data set
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
pred=GN_classifier.predict(X_test)
print(classification_report(y_test,pred))
print()
print('confusion_matrix: \n',confusion_matrix(y_test,pred))
print()
print('accuracy: \n',accuracy_score(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       870
           1       0.97      1.00      0.98       269

    accuracy                           0.99      1139
   macro avg       0.98      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139


confusion_matrix: 
 [[862   8]
 [  1 268]]

accuracy: 
 0.9920983318700615
